version: '3'
services:
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "4001:3000"
    volumes:
      - /app/node_modules
      - C:\Users\nikhilsharma02\Desktop\docker\frontend:/app
  test:
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - /app/node_modules
      - C:\Users\nikhilsharma02\Desktop\docker\frontend:/app
    command: ["npm","run","test"]
